repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language: python

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed.
      - id: check-ast # Simply check whether files parse as valid python
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types.
      - id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
      - id: check-docstring-first # Checks for a common error of placing code before the docstring.
      - id: check-executables-have-shebangs # Checks that non-binary executables have a proper shebang.
      - id: check-json # Attempts to load all json files to verify syntax.
      - id: check-merge-conflict # Check for files that contain merge conflict strings.
      - id: check-shebang-scripts-are-executable # Checks that scripts with shebangs are executable.
      - id: check-symlinks # Checks for symlinks which do not point to anything.
      - id: check-toml # Attempts to load all TOML files to verify syntax.
      - id: check-vcs-permalinks # Ensures that links to vcs websites are permalinks.
      - id: check-xml # Attempts to load all xml files to verify syntax.
      - id: check-yaml # Attempts to load all yaml files to verify syntax.
      - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.
      - id: destroyed-symlinks # Detects symlinks which are changed to regular files with a content of a path which that symlink was pointing to.
      # - id: detect-aws-credentials # Checks for the existence of AWS secrets that you have set up with the AWS CLI.
      - id: detect-private-key # Checks for the existence of private keys.
      # - id: double-quote-string-fixer # This hook replaces double quoted strings with single quoted strings.
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: fix-byte-order-marker # Removes UTF-8 byte order marker
      - id: fix-encoding-pragma # Add # -*- coding: utf-8 -*- to the top of python files.
      - id: forbid-submodules # forbids any submodules in the repository.
      - id: mixed-line-ending # Replaces or checks mixed line ending.
      - id: name-tests-test # verifies that test files are named correctly.
        args: [--pytest-test-first]
      # - id: no-commit-to-branch # Protect specific branches from direct checkins.
      #   args: [--branch, main]
      - id: pretty-format-json # Checks that all your JSON files are pretty.
        args: [--autofix, --indent, "4", --no-ensure-ascii, --no-sort-keys]
      - id: requirements-txt-fixer # Sorts entries in requirements.txt and constraints.txt and removes incorrect entry for pkg-resources==0.0.0
      # - id: sort-simple-yaml # Sorts simple YAML files which consist only of top-level keys, preserving comments and blocks.
      #   files: ^config/simple/
      # - id: trailing-whitespace # Trims trailing whitespace.
      #   args: [--markdown-linebreak-ext=md]

  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   # Ruff version.
  #   rev: "v0.0.263"
  #   hooks:
  #     - id: ruff

  - repo: local
    hooks:
      - id: qa
        name: qa
        entry: bash -c './qa-in-docker.sh'
        language: system

default_language_version:
  python: python3.9
