from django.http import HttpRequest as HttpRequest

def layout_settings(request: HttpRequest) -> dict: ...
def top_menu(request: HttpRequest) -> dict: ...
def user(request: HttpRequest) -> dict: ...
def sidebar_menu(request: HttpRequest) -> dict: ...
def messages(request: HttpRequest) -> dict: ...
def notifications(request: HttpRequest) -> dict: ...
