# https://beta.ruff.rs/docs/settings/
# https://google.github.io/styleguide/pyguide.html

[tool.ruff]
line-length = 120
target-version = "py39"
show-source = true
show-fixes = true
fix = true


[tool.ruff.flake8-annotations]
allow-star-arg-any = true

[tool.ruff.mccabe]
max-complexity = 5

[tool.ruff.pycodestyle]
max-doc-length = 120

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
multi_line_output = 3
force_grid_wrap = 0

[tool.pytest]
filterwarnings = "ignore::urllib3.exceptions.InsecureRequestWarning"
addopts = "--cov-report term --cov-report html:coverage --cov-report xml:coverage/cobertura-coverage.xml "

[tool.mypy]


[[tool.mypy.overrides]]
module = "django.*"
ignore_missing_imports = true
