from django.contrib.admin.widgets import (
    AdminBigIntegerFieldWidget,
    AdminDateWidget,
    AdminEmailInputWidget,
    AdminFileWidget,
    AdminIntegerFieldWidget,
    AdminRadioSelect,
    AdminSplitDateTime,
    AdminTextInputWidget,
    AdminTextareaWidget,
    AdminTimeWidget,
    AdminURLFieldWidget,
    AutocompleteMixin,
    AutocompleteSelect,
    AutocompleteSelectMultiple,
    ForeignKeyRawIdWidget,
    ManyToManyRawIdWidget,
    RelatedFieldWidgetWrapper,
)
from typing import Union

class AdminLTEDateWidget(AdminDateWidget): ...

class AdminLTETimeWidget(AdminTimeWidget):
    def __init__(self, attrs: Union[dict, None] = ..., format: Union[str, None] = ...) -> None: ...

class AdminLTESplitDateTime(AdminSplitDateTime): ...
class AdminLTERadioSelect(AdminRadioSelect): ...
class AdminLTEFileWidget(AdminFileWidget): ...
class AdminLTEForeignKeyRawIdWidget(ForeignKeyRawIdWidget): ...
class AdminLTEManyToManyRawIdWidget(ManyToManyRawIdWidget): ...
class AdminLTERelatedFieldWidgetWrapper(RelatedFieldWidgetWrapper): ...

class AdminLTETextareaWidget(AdminTextareaWidget):
    def __init__(self, attrs: Union[dict, None] = ...) -> None: ...

class AdminLTETextInputWidget(AdminTextInputWidget):
    def __init__(self, attrs: Union[dict, None] = ...) -> None: ...

class AdminLTEEmailInputWidget(AdminEmailInputWidget):
    def __init__(self, attrs: Union[dict, None] = ...) -> None: ...

class AdminLTEURLFieldWidget(AdminURLFieldWidget): ...

class AdminLTEIntegerFieldWidget(AdminIntegerFieldWidget):
    def __init__(self, attrs: Union[dict, None] = ...) -> None: ...

class AdminLTEBigIntegerFieldWidget(AdminBigIntegerFieldWidget):
    def __init__(self, attrs: Union[dict, None] = ...) -> None: ...

class AdminLTEUUIDInputWidget(AutocompleteMixin):
    def __init__(self, attrs: Union[dict, None] = ...) -> None: ...

class AdminLTEAutocompleteMixin(AutocompleteMixin): ...
class AdminLTEAutocompleteSelect(AutocompleteSelect): ...
class AdminLTEAutocompleteSelectMultiple(AutocompleteSelectMultiple): ...
