# Generated by Django 4.0.2 on 2022-02-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alldatatypes',
            name='null_boolean_field',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='file_path_field',
            field=models.FilePathField(path='/Users/kelson/devel/pessoal/django-adminlte3'),
        ),
    ]
