# Generated by Django 4.0.2 on 2022-05-05 19:16

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example', '0002_alldatatypes_null_boolean_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alldatatypes',
            name='boolean_field',
        ),
        migrations.RemoveField(
            model_name='alldatatypes',
            name='null_boolean_field',
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='date_field',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))]),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='desconhecido',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='file_path_field',
            field=models.FilePathField(path=pathlib.PurePosixPath('/home/danilo/djangoAdminlte/django-adminlte3')),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='foreign_key_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='many_to_many_field',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Permission'),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='nao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='one_to_one_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alldatatypes',
            name='sim',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
