# -*- coding: utf-8 -*-
# Generated by Django 4.2 on 2023-04-29 23:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pathlib


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllDataTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("small_integer_field", models.SmallIntegerField()),
                ("integer_field", models.IntegerField()),
                ("big_integer_field", models.BigIntegerField()),
                ("positive_small_integer_field", models.PositiveSmallIntegerField()),
                ("positive_integer_field", models.PositiveIntegerField()),
                ("positive_big_integer_field", models.PositiveBigIntegerField()),
                ("decimal_field", models.DecimalField(decimal_places=2, max_digits=10)),
                ("float_field", models.FloatField()),
                ("char_field", models.CharField(max_length=255)),
                ("text_field", models.TextField()),
                ("slug_field", models.SlugField()),
                (
                    "date_field",
                    models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))]),
                ),
                ("time", models.TimeField()),
                ("date_time_field", models.DateTimeField()),
                ("duration_field", models.DurationField()),
                ("email_field", models.EmailField(max_length=254)),
                ("generic_ip_address_field", models.GenericIPAddressField()),
                ("url_field", models.URLField()),
                ("binary_field", models.BinaryField()),
                (
                    "file_path_field",
                    models.FilePathField(path=pathlib.PurePosixPath("/app/example_project")),
                ),
                ("file_field", models.FileField(upload_to="")),
                ("image_field", models.ImageField(upload_to="")),
                ("desconhecido", models.BooleanField()),
                ("sim", models.BooleanField()),
                ("nao", models.BooleanField()),
                (
                    "foreign_key_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "many_to_many_field",
                    models.ManyToManyField(blank=True, null=True, to="auth.permission"),
                ),
                (
                    "one_to_one_field",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
